sudo: required
services:
  - docker

before_install:
  - docker build -t gkhunashvili109/react-test -f ./client/Dockerfile.dev ./client

scrpit:
  - docker run -e CI=true gkhunashvili109/react-test npm run test

after_success:
  - docker build -t gkhunashvili109/multi-client ./client
  - docker build -t gkhunashvili109/multi-nginx ./nginx
  - docker build -t gkhunashvili109/multi-server ./server
  - docker build -t gkhunashvili109/multi-worker ./worker
  #login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push to docker CLI
  - docker push gkhunashvili109/multi-client
  - docker push gkhunashvili109/multi-nginx
  - docker push gkhunashvili109/multi-server
  - docker push gkhunashvili109/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-295107012244
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY