sudo: required
services:
  - docker

before_install:
  - docker build -t gkhunashvili109/react-test -f ./client/Dockerfile.dev ./client

scrpit:
  - docker run -e CI=true gkhunashvili109/react-test npm run test

after_success:
  - docker build -t gkhunashvili109/multi-client ./client
  - docker build -t gkhunashvili109/multi-nginx ./nginx
  - docker build -t gkhunashvili109/multi-server ./server
  - docker build -t gkhunashvili109/multi-worker ./worker
  #login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push to docker CLI
  - docker push gkhunashvili109/multi-client
  - docker push gkhunashvili109/multi-nginx
  - docker push gkhunashvili109/multi-server
  - docker push gkhunashvili109/multi-worker